export var E2BIG = 7;
export var EACCES = 13;
export var EADDRINUSE = 100;
export var EADDRNOTAVAIL = 101;
export var EAFNOSUPPORT = 102;
export var EAGAIN = 11;
export var EALREADY = 103;
export var EBADF = 9;
export var EBADMSG = 104;
export var EBUSY = 16;
export var ECANCELED = 105;
export var ECHILD = 10;
export var ECONNABORTED = 106;
export var ECONNREFUSED = 107;
export var ECONNRESET = 108;
export var EDEADLK = 36;
export var EDESTADDRREQ = 109;
export var EDOM = 33;
export var EEXIST = 17;
export var EFAULT = 14;
export var EFBIG = 27;
export var EHOSTUNREACH = 110;
export var EIDRM = 111;
export var EILSEQ = 42;
export var EINPROGRESS = 112;
export var EINTR = 4;
export var EINVAL = 22;
export var EIO = 5;
export var EISCONN = 113;
export var EISDIR = 21;
export var ELOOP = 114;
export var EMFILE = 24;
export var EMLINK = 31;
export var EMSGSIZE = 115;
export var ENAMETOOLONG = 38;
export var ENETDOWN = 116;
export var ENETRESET = 117;
export var ENETUNREACH = 118;
export var ENFILE = 23;
export var ENOBUFS = 119;
export var ENODATA = 120;
export var ENODEV = 19;
export var ENOENT = 2;
export var ENOEXEC = 8;
export var ENOLCK = 39;
export var ENOLINK = 121;
export var ENOMEM = 12;
export var ENOMSG = 122;
export var ENOPROTOOPT = 123;
export var ENOSPC = 28;
export var ENOSR = 124;
export var ENOSTR = 125;
export var ENOSYS = 40;
export var ENOTCONN = 126;
export var ENOTDIR = 20;
export var ENOTEMPTY = 41;
export var ENOTSOCK = 128;
export var ENOTSUP = 129;
export var ENOTTY = 25;
export var ENXIO = 6;
export var EOPNOTSUPP = 130;
export var EOVERFLOW = 132;
export var EPERM = 1;
export var EPIPE = 32;
export var EPROTO = 134;
export var EPROTONOSUPPORT = 135;
export var EPROTOTYPE = 136;
export var ERANGE = 34;
export var EROFS = 30;
export var ESPIPE = 29;
export var ESRCH = 3;
export var ETIME = 137;
export var ETIMEDOUT = 138;
export var ETXTBSY = 139;
export var EWOULDBLOCK = 140;
export var EXDEV = 18;
export var WSAEINTR = 10004;
export var WSAEBADF = 10009;
export var WSAEACCES = 10013;
export var WSAEFAULT = 10014;
export var WSAEINVAL = 10022;
export var WSAEMFILE = 10024;
export var WSAEWOULDBLOCK = 10035;
export var WSAEINPROGRESS = 10036;
export var WSAEALREADY = 10037;
export var WSAENOTSOCK = 10038;
export var WSAEDESTADDRREQ = 10039;
export var WSAEMSGSIZE = 10040;
export var WSAEPROTOTYPE = 10041;
export var WSAENOPROTOOPT = 10042;
export var WSAEPROTONOSUPPORT = 10043;
export var WSAESOCKTNOSUPPORT = 10044;
export var WSAEOPNOTSUPP = 10045;
export var WSAEPFNOSUPPORT = 10046;
export var WSAEAFNOSUPPORT = 10047;
export var WSAEADDRINUSE = 10048;
export var WSAEADDRNOTAVAIL = 10049;
export var WSAENETDOWN = 10050;
export var WSAENETUNREACH = 10051;
export var WSAENETRESET = 10052;
export var WSAECONNABORTED = 10053;
export var WSAECONNRESET = 10054;
export var WSAENOBUFS = 10055;
export var WSAEISCONN = 10056;
export var WSAENOTCONN = 10057;
export var WSAESHUTDOWN = 10058;
export var WSAETOOMANYREFS = 10059;
export var WSAETIMEDOUT = 10060;
export var WSAECONNREFUSED = 10061;
export var WSAELOOP = 10062;
export var WSAENAMETOOLONG = 10063;
export var WSAEHOSTDOWN = 10064;
export var WSAEHOSTUNREACH = 10065;
export var WSAENOTEMPTY = 10066;
export var WSAEPROCLIM = 10067;
export var WSAEUSERS = 10068;
export var WSAEDQUOT = 10069;
export var WSAESTALE = 10070;
export var WSAEREMOTE = 10071;
export var WSASYSNOTREADY = 10091;
export var WSAVERNOTSUPPORTED = 10092;
export var WSANOTINITIALISED = 10093;
export var WSAEDISCON = 10101;
export var WSAENOMORE = 10102;
export var WSAECANCELLED = 10103;
export var WSAEINVALIDPROCTABLE = 10104;
export var WSAEINVALIDPROVIDER = 10105;
export var WSAEPROVIDERFAILEDINIT = 10106;
export var WSASYSCALLFAILURE = 10107;
export var WSASERVICE_NOT_FOUND = 10108;
export var WSATYPE_NOT_FOUND = 10109;
export var WSA_E_NO_MORE = 10110;
export var WSA_E_CANCELLED = 10111;
export var WSAEREFUSED = 10112;
export var PRIORITY_LOW = 19;
export var PRIORITY_BELOW_NORMAL = 10;
export var PRIORITY_NORMAL = 0;
export var PRIORITY_ABOVE_NORMAL = -7;
export var PRIORITY_HIGH = -14;
export var PRIORITY_HIGHEST = -20;
export var SIGHUP = 1;
export var SIGINT = 2;
export var SIGILL = 4;
export var SIGABRT = 22;
export var SIGFPE = 8;
export var SIGKILL = 9;
export var SIGSEGV = 11;
export var SIGTERM = 15;
export var SIGBREAK = 21;
export var SIGWINCH = 28;
export var UV_FS_SYMLINK_DIR = 1;
export var UV_FS_SYMLINK_JUNCTION = 2;
export var O_RDONLY = 0;
export var O_WRONLY = 1;
export var O_RDWR = 2;
export var UV_DIRENT_UNKNOWN = 0;
export var UV_DIRENT_FILE = 1;
export var UV_DIRENT_DIR = 2;
export var UV_DIRENT_LINK = 3;
export var UV_DIRENT_FIFO = 4;
export var UV_DIRENT_SOCKET = 5;
export var UV_DIRENT_CHAR = 6;
export var UV_DIRENT_BLOCK = 7;
export var S_IFMT = 61440;
export var S_IFREG = 32768;
export var S_IFDIR = 16384;
export var S_IFCHR = 8192;
export var S_IFLNK = 40960;
export var O_CREAT = 256;
export var O_EXCL = 1024;
export var UV_FS_O_FILEMAP = 536870912;
export var O_TRUNC = 512;
export var O_APPEND = 8;
export var F_OK = 0;
export var R_OK = 4;
export var W_OK = 2;
export var X_OK = 1;
export var UV_FS_COPYFILE_EXCL = 1;
export var COPYFILE_EXCL = 1;
export var UV_FS_COPYFILE_FICLONE = 2;
export var COPYFILE_FICLONE = 2;
export var UV_FS_COPYFILE_FICLONE_FORCE = 4;
export var COPYFILE_FICLONE_FORCE = 4;
export var OPENSSL_VERSION_NUMBER = 269488239;
export var SSL_OP_ALL = 2147485780;
export var SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION = 262144;
export var SSL_OP_CIPHER_SERVER_PREFERENCE = 4194304;
export var SSL_OP_CISCO_ANYCONNECT = 32768;
export var SSL_OP_COOKIE_EXCHANGE = 8192;
export var SSL_OP_CRYPTOPRO_TLSEXT_BUG = 2147483648;
export var SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS = 2048;
export var SSL_OP_EPHEMERAL_RSA = 0;
export var SSL_OP_LEGACY_SERVER_CONNECT = 4;
export var SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER = 0;
export var SSL_OP_MICROSOFT_SESS_ID_BUG = 0;
export var SSL_OP_MSIE_SSLV2_RSA_PADDING = 0;
export var SSL_OP_NETSCAPE_CA_DN_BUG = 0;
export var SSL_OP_NETSCAPE_CHALLENGE_BUG = 0;
export var SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG = 0;
export var SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG = 0;
export var SSL_OP_NO_COMPRESSION = 131072;
export var SSL_OP_NO_QUERY_MTU = 4096;
export var SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION = 65536;
export var SSL_OP_NO_SSLv2 = 0;
export var SSL_OP_NO_SSLv3 = 33554432;
export var SSL_OP_NO_TICKET = 16384;
export var SSL_OP_NO_TLSv1 = 67108864;
export var SSL_OP_NO_TLSv1_1 = 268435456;
export var SSL_OP_NO_TLSv1_2 = 134217728;
export var SSL_OP_PKCS1_CHECK_1 = 0;
export var SSL_OP_PKCS1_CHECK_2 = 0;
export var SSL_OP_SINGLE_DH_USE = 0;
export var SSL_OP_SINGLE_ECDH_USE = 0;
export var SSL_OP_SSLEAY_080_CLIENT_DH_BUG = 0;
export var SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG = 0;
export var SSL_OP_TLS_BLOCK_PADDING_BUG = 0;
export var SSL_OP_TLS_D5_BUG = 0;
export var SSL_OP_TLS_ROLLBACK_BUG = 8388608;
export var ENGINE_METHOD_RSA = 1;
export var ENGINE_METHOD_DSA = 2;
export var ENGINE_METHOD_DH = 4;
export var ENGINE_METHOD_RAND = 8;
export var ENGINE_METHOD_EC = 2048;
export var ENGINE_METHOD_CIPHERS = 64;
export var ENGINE_METHOD_DIGESTS = 128;
export var ENGINE_METHOD_PKEY_METHS = 512;
export var ENGINE_METHOD_PKEY_ASN1_METHS = 1024;
export var ENGINE_METHOD_ALL = 65535;
export var ENGINE_METHOD_NONE = 0;
export var DH_CHECK_P_NOT_SAFE_PRIME = 2;
export var DH_CHECK_P_NOT_PRIME = 1;
export var DH_UNABLE_TO_CHECK_GENERATOR = 4;
export var DH_NOT_SUITABLE_GENERATOR = 8;
export var ALPN_ENABLED = 1;
export var RSA_PKCS1_PADDING = 1;
export var RSA_SSLV23_PADDING = 2;
export var RSA_NO_PADDING = 3;
export var RSA_PKCS1_OAEP_PADDING = 4;
export var RSA_X931_PADDING = 5;
export var RSA_PKCS1_PSS_PADDING = 6;
export var RSA_PSS_SALTLEN_DIGEST = -1;
export var RSA_PSS_SALTLEN_MAX_SIGN = -2;
export var RSA_PSS_SALTLEN_AUTO = -2;
export var defaultCoreCipherList = "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA";
export var TLS1_VERSION = 769;
export var TLS1_1_VERSION = 770;
export var TLS1_2_VERSION = 771;
export var TLS1_3_VERSION = 772;
export var POINT_CONVERSION_COMPRESSED = 2;
export var POINT_CONVERSION_UNCOMPRESSED = 4;
export var POINT_CONVERSION_HYBRID = 6;
export default {
  E2BIG: E2BIG,
  EACCES: EACCES,
  EADDRINUSE: EADDRINUSE,
  EADDRNOTAVAIL: EADDRNOTAVAIL,
  EAFNOSUPPORT: EAFNOSUPPORT,
  EAGAIN: EAGAIN,
  EALREADY: EALREADY,
  EBADF: EBADF,
  EBADMSG: EBADMSG,
  EBUSY: EBUSY,
  ECANCELED: ECANCELED,
  ECHILD: ECHILD,
  ECONNABORTED: ECONNABORTED,
  ECONNREFUSED: ECONNREFUSED,
  ECONNRESET: ECONNRESET,
  EDEADLK: EDEADLK,
  EDESTADDRREQ: EDESTADDRREQ,
  EDOM: EDOM,
  EEXIST: EEXIST,
  EFAULT: EFAULT,
  EFBIG: EFBIG,
  EHOSTUNREACH: EHOSTUNREACH,
  EIDRM: EIDRM,
  EILSEQ: EILSEQ,
  EINPROGRESS: EINPROGRESS,
  EINTR: EINTR,
  EINVAL: EINVAL,
  EIO: EIO,
  EISCONN: EISCONN,
  EISDIR: EISDIR,
  ELOOP: ELOOP,
  EMFILE: EMFILE,
  EMLINK: EMLINK,
  EMSGSIZE: EMSGSIZE,
  ENAMETOOLONG: ENAMETOOLONG,
  ENETDOWN: ENETDOWN,
  ENETRESET: ENETRESET,
  ENETUNREACH: ENETUNREACH,
  ENFILE: ENFILE,
  ENOBUFS: ENOBUFS,
  ENODATA: ENODATA,
  ENODEV: ENODEV,
  ENOENT: ENOENT,
  ENOEXEC: ENOEXEC,
  ENOLCK: ENOLCK,
  ENOLINK: ENOLINK,
  ENOMEM: ENOMEM,
  ENOMSG: ENOMSG,
  ENOPROTOOPT: ENOPROTOOPT,
  ENOSPC: ENOSPC,
  ENOSR: ENOSR,
  ENOSTR: ENOSTR,
  ENOSYS: ENOSYS,
  ENOTCONN: ENOTCONN,
  ENOTDIR: ENOTDIR,
  ENOTEMPTY: ENOTEMPTY,
  ENOTSOCK: ENOTSOCK,
  ENOTSUP: ENOTSUP,
  ENOTTY: ENOTTY,
  ENXIO: ENXIO,
  EOPNOTSUPP: EOPNOTSUPP,
  EOVERFLOW: EOVERFLOW,
  EPERM: EPERM,
  EPIPE: EPIPE,
  EPROTO: EPROTO,
  EPROTONOSUPPORT: EPROTONOSUPPORT,
  EPROTOTYPE: EPROTOTYPE,
  ERANGE: ERANGE,
  EROFS: EROFS,
  ESPIPE: ESPIPE,
  ESRCH: ESRCH,
  ETIME: ETIME,
  ETIMEDOUT: ETIMEDOUT,
  ETXTBSY: ETXTBSY,
  EWOULDBLOCK: EWOULDBLOCK,
  EXDEV: EXDEV,
  WSAEINTR: WSAEINTR,
  WSAEBADF: WSAEBADF,
  WSAEACCES: WSAEACCES,
  WSAEFAULT: WSAEFAULT,
  WSAEINVAL: WSAEINVAL,
  WSAEMFILE: WSAEMFILE,
  WSAEWOULDBLOCK: WSAEWOULDBLOCK,
  WSAEINPROGRESS: WSAEINPROGRESS,
  WSAEALREADY: WSAEALREADY,
  WSAENOTSOCK: WSAENOTSOCK,
  WSAEDESTADDRREQ: WSAEDESTADDRREQ,
  WSAEMSGSIZE: WSAEMSGSIZE,
  WSAEPROTOTYPE: WSAEPROTOTYPE,
  WSAENOPROTOOPT: WSAENOPROTOOPT,
  WSAEPROTONOSUPPORT: WSAEPROTONOSUPPORT,
  WSAESOCKTNOSUPPORT: WSAESOCKTNOSUPPORT,
  WSAEOPNOTSUPP: WSAEOPNOTSUPP,
  WSAEPFNOSUPPORT: WSAEPFNOSUPPORT,
  WSAEAFNOSUPPORT: WSAEAFNOSUPPORT,
  WSAEADDRINUSE: WSAEADDRINUSE,
  WSAEADDRNOTAVAIL: WSAEADDRNOTAVAIL,
  WSAENETDOWN: WSAENETDOWN,
  WSAENETUNREACH: WSAENETUNREACH,
  WSAENETRESET: WSAENETRESET,
  WSAECONNABORTED: WSAECONNABORTED,
  WSAECONNRESET: WSAECONNRESET,
  WSAENOBUFS: WSAENOBUFS,
  WSAEISCONN: WSAEISCONN,
  WSAENOTCONN: WSAENOTCONN,
  WSAESHUTDOWN: WSAESHUTDOWN,
  WSAETOOMANYREFS: WSAETOOMANYREFS,
  WSAETIMEDOUT: WSAETIMEDOUT,
  WSAECONNREFUSED: WSAECONNREFUSED,
  WSAELOOP: WSAELOOP,
  WSAENAMETOOLONG: WSAENAMETOOLONG,
  WSAEHOSTDOWN: WSAEHOSTDOWN,
  WSAEHOSTUNREACH: WSAEHOSTUNREACH,
  WSAENOTEMPTY: WSAENOTEMPTY,
  WSAEPROCLIM: WSAEPROCLIM,
  WSAEUSERS: WSAEUSERS,
  WSAEDQUOT: WSAEDQUOT,
  WSAESTALE: WSAESTALE,
  WSAEREMOTE: WSAEREMOTE,
  WSASYSNOTREADY: WSASYSNOTREADY,
  WSAVERNOTSUPPORTED: WSAVERNOTSUPPORTED,
  WSANOTINITIALISED: WSANOTINITIALISED,
  WSAEDISCON: WSAEDISCON,
  WSAENOMORE: WSAENOMORE,
  WSAECANCELLED: WSAECANCELLED,
  WSAEINVALIDPROCTABLE: WSAEINVALIDPROCTABLE,
  WSAEINVALIDPROVIDER: WSAEINVALIDPROVIDER,
  WSAEPROVIDERFAILEDINIT: WSAEPROVIDERFAILEDINIT,
  WSASYSCALLFAILURE: WSASYSCALLFAILURE,
  WSASERVICE_NOT_FOUND: WSASERVICE_NOT_FOUND,
  WSATYPE_NOT_FOUND: WSATYPE_NOT_FOUND,
  WSA_E_NO_MORE: WSA_E_NO_MORE,
  WSA_E_CANCELLED: WSA_E_CANCELLED,
  WSAEREFUSED: WSAEREFUSED,
  PRIORITY_LOW: PRIORITY_LOW,
  PRIORITY_BELOW_NORMAL: PRIORITY_BELOW_NORMAL,
  PRIORITY_NORMAL: PRIORITY_NORMAL,
  PRIORITY_ABOVE_NORMAL: PRIORITY_ABOVE_NORMAL,
  PRIORITY_HIGH: PRIORITY_HIGH,
  PRIORITY_HIGHEST: PRIORITY_HIGHEST,
  SIGHUP: SIGHUP,
  SIGINT: SIGINT,
  SIGILL: SIGILL,
  SIGABRT: SIGABRT,
  SIGFPE: SIGFPE,
  SIGKILL: SIGKILL,
  SIGSEGV: SIGSEGV,
  SIGTERM: SIGTERM,
  SIGBREAK: SIGBREAK,
  SIGWINCH: SIGWINCH,
  UV_FS_SYMLINK_DIR: UV_FS_SYMLINK_DIR,
  UV_FS_SYMLINK_JUNCTION: UV_FS_SYMLINK_JUNCTION,
  O_RDONLY: O_RDONLY,
  O_WRONLY: O_WRONLY,
  O_RDWR: O_RDWR,
  UV_DIRENT_UNKNOWN: UV_DIRENT_UNKNOWN,
  UV_DIRENT_FILE: UV_DIRENT_FILE,
  UV_DIRENT_DIR: UV_DIRENT_DIR,
  UV_DIRENT_LINK: UV_DIRENT_LINK,
  UV_DIRENT_FIFO: UV_DIRENT_FIFO,
  UV_DIRENT_SOCKET: UV_DIRENT_SOCKET,
  UV_DIRENT_CHAR: UV_DIRENT_CHAR,
  UV_DIRENT_BLOCK: UV_DIRENT_BLOCK,
  S_IFMT: S_IFMT,
  S_IFREG: S_IFREG,
  S_IFDIR: S_IFDIR,
  S_IFCHR: S_IFCHR,
  S_IFLNK: S_IFLNK,
  O_CREAT: O_CREAT,
  O_EXCL: O_EXCL,
  UV_FS_O_FILEMAP: UV_FS_O_FILEMAP,
  O_TRUNC: O_TRUNC,
  O_APPEND: O_APPEND,
  F_OK: F_OK,
  R_OK: R_OK,
  W_OK: W_OK,
  X_OK: X_OK,
  UV_FS_COPYFILE_EXCL: UV_FS_COPYFILE_EXCL,
  COPYFILE_EXCL: COPYFILE_EXCL,
  UV_FS_COPYFILE_FICLONE: UV_FS_COPYFILE_FICLONE,
  COPYFILE_FICLONE: COPYFILE_FICLONE,
  UV_FS_COPYFILE_FICLONE_FORCE: UV_FS_COPYFILE_FICLONE_FORCE,
  COPYFILE_FICLONE_FORCE: COPYFILE_FICLONE_FORCE,
  OPENSSL_VERSION_NUMBER: OPENSSL_VERSION_NUMBER,
  SSL_OP_ALL: SSL_OP_ALL,
  SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION: SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION,
  SSL_OP_CIPHER_SERVER_PREFERENCE: SSL_OP_CIPHER_SERVER_PREFERENCE,
  SSL_OP_CISCO_ANYCONNECT: SSL_OP_CISCO_ANYCONNECT,
  SSL_OP_COOKIE_EXCHANGE: SSL_OP_COOKIE_EXCHANGE,
  SSL_OP_CRYPTOPRO_TLSEXT_BUG: SSL_OP_CRYPTOPRO_TLSEXT_BUG,
  SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS: SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS,
  SSL_OP_EPHEMERAL_RSA: SSL_OP_EPHEMERAL_RSA,
  SSL_OP_LEGACY_SERVER_CONNECT: SSL_OP_LEGACY_SERVER_CONNECT,
  SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER: SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER,
  SSL_OP_MICROSOFT_SESS_ID_BUG: SSL_OP_MICROSOFT_SESS_ID_BUG,
  SSL_OP_MSIE_SSLV2_RSA_PADDING: SSL_OP_MSIE_SSLV2_RSA_PADDING,
  SSL_OP_NETSCAPE_CA_DN_BUG: SSL_OP_NETSCAPE_CA_DN_BUG,
  SSL_OP_NETSCAPE_CHALLENGE_BUG: SSL_OP_NETSCAPE_CHALLENGE_BUG,
  SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG: SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG,
  SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG: SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG,
  SSL_OP_NO_COMPRESSION: SSL_OP_NO_COMPRESSION,
  SSL_OP_NO_QUERY_MTU: SSL_OP_NO_QUERY_MTU,
  SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION: SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION,
  SSL_OP_NO_SSLv2: SSL_OP_NO_SSLv2,
  SSL_OP_NO_SSLv3: SSL_OP_NO_SSLv3,
  SSL_OP_NO_TICKET: SSL_OP_NO_TICKET,
  SSL_OP_NO_TLSv1: SSL_OP_NO_TLSv1,
  SSL_OP_NO_TLSv1_1: SSL_OP_NO_TLSv1_1,
  SSL_OP_NO_TLSv1_2: SSL_OP_NO_TLSv1_2,
  SSL_OP_PKCS1_CHECK_1: SSL_OP_PKCS1_CHECK_1,
  SSL_OP_PKCS1_CHECK_2: SSL_OP_PKCS1_CHECK_2,
  SSL_OP_SINGLE_DH_USE: SSL_OP_SINGLE_DH_USE,
  SSL_OP_SINGLE_ECDH_USE: SSL_OP_SINGLE_ECDH_USE,
  SSL_OP_SSLEAY_080_CLIENT_DH_BUG: SSL_OP_SSLEAY_080_CLIENT_DH_BUG,
  SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG: SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG,
  SSL_OP_TLS_BLOCK_PADDING_BUG: SSL_OP_TLS_BLOCK_PADDING_BUG,
  SSL_OP_TLS_D5_BUG: SSL_OP_TLS_D5_BUG,
  SSL_OP_TLS_ROLLBACK_BUG: SSL_OP_TLS_ROLLBACK_BUG,
  ENGINE_METHOD_RSA: ENGINE_METHOD_RSA,
  ENGINE_METHOD_DSA: ENGINE_METHOD_DSA,
  ENGINE_METHOD_DH: ENGINE_METHOD_DH,
  ENGINE_METHOD_RAND: ENGINE_METHOD_RAND,
  ENGINE_METHOD_EC: ENGINE_METHOD_EC,
  ENGINE_METHOD_CIPHERS: ENGINE_METHOD_CIPHERS,
  ENGINE_METHOD_DIGESTS: ENGINE_METHOD_DIGESTS,
  ENGINE_METHOD_PKEY_METHS: ENGINE_METHOD_PKEY_METHS,
  ENGINE_METHOD_PKEY_ASN1_METHS: ENGINE_METHOD_PKEY_ASN1_METHS,
  ENGINE_METHOD_ALL: ENGINE_METHOD_ALL,
  ENGINE_METHOD_NONE: ENGINE_METHOD_NONE,
  DH_CHECK_P_NOT_SAFE_PRIME: DH_CHECK_P_NOT_SAFE_PRIME,
  DH_CHECK_P_NOT_PRIME: DH_CHECK_P_NOT_PRIME,
  DH_UNABLE_TO_CHECK_GENERATOR: DH_UNABLE_TO_CHECK_GENERATOR,
  DH_NOT_SUITABLE_GENERATOR: DH_NOT_SUITABLE_GENERATOR,
  ALPN_ENABLED: ALPN_ENABLED,
  RSA_PKCS1_PADDING: RSA_PKCS1_PADDING,
  RSA_SSLV23_PADDING: RSA_SSLV23_PADDING,
  RSA_NO_PADDING: RSA_NO_PADDING,
  RSA_PKCS1_OAEP_PADDING: RSA_PKCS1_OAEP_PADDING,
  RSA_X931_PADDING: RSA_X931_PADDING,
  RSA_PKCS1_PSS_PADDING: RSA_PKCS1_PSS_PADDING,
  RSA_PSS_SALTLEN_DIGEST: RSA_PSS_SALTLEN_DIGEST,
  RSA_PSS_SALTLEN_MAX_SIGN: RSA_PSS_SALTLEN_MAX_SIGN,
  RSA_PSS_SALTLEN_AUTO: RSA_PSS_SALTLEN_AUTO,
  defaultCoreCipherList: defaultCoreCipherList,
  TLS1_VERSION: TLS1_VERSION,
  TLS1_1_VERSION: TLS1_1_VERSION,
  TLS1_2_VERSION: TLS1_2_VERSION,
  TLS1_3_VERSION: TLS1_3_VERSION,
  POINT_CONVERSION_COMPRESSED: POINT_CONVERSION_COMPRESSED,
  POINT_CONVERSION_UNCOMPRESSED: POINT_CONVERSION_UNCOMPRESSED,
  POINT_CONVERSION_HYBRID: POINT_CONVERSION_HYBRID
};
